## Configura diferente ambientes como: PRD, QAS,DEV
spring.application.name = "Financeiro Pessoa Versao 1"
#Porta do Tomcat
server.port=8081
## PostgreSQL
#Link de chamada 
server.servlet.context-path=/financapessoal
## PostgreSQL
spring.jpa.database=POSTGRESQL


spring.datasource.url=jdbc:postgresql://localhost:5432/DEVFinanceiro
spring.datasource.username=postgres
spring.datasource.password=saturno

#Hibernate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

